
---
- name: installing tomcat to servers 
  hosts: webservers
  tasks:
    - name: installing java 
      apt:
        name: openjdk-13-jre-headless
        state: present
        update_cache: yes
    - name: create the user tomcat
      become: yes
      user:
        name: tomcat
        state: present
    - name: create a directory /opt/tomcat
      become: yes
      file:
        path: /opt/tomcat
        state: directory
        recurse: yes
        mode: '0755'
        owner: tomcat
    - name: download tomcat
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.2/bin/apache-tomcat-10.1.2.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra__opts: [--strip-components=1]

    - name: creating a service file
      become: yes
      copy:
        content: |-
          [Unit]
          Description=Tomcat
          After=network.target
          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment="JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"
          Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
          Environment="CATALINA_BASE=/opt/tomcat"
          Environment="CATALINA_HOME=/opt/tomcat"
          Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          RestartSec=10
          Restart=always
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service
    - name: enable and start tomcat
      become: yes
      systemd:
        name: tomcat
        enabled: no
        state: started
    - name: Task 4 Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp
        state: enabled